add cloud init
slashrelativepath/relativepath-cycle-3 pull request #21
Opened 2023-05-18 23:07 UTC by Roadlyfe

2023-05-20 00:01 UTC, stephenlauck requested changes

2023-05-20 00:01 UTC, stephenlauck commented on cloud-init.yaml
> +  - name: adam
How can we make this more dynamic? Are there shell variables we could use here?

2023-05-20 00:01 UTC, stephenlauck commented on cloud-init.yaml
> +      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOauAfXt5gKJI4uRbpH+ewEFEeyNA5FC9mKd9U+dJVKO adamsmith@Adams-MacBook-Air.local
How can we get the key into this file or maybe write the whole cloud-init.yaml each time we create a new set of keys?

2023-05-20 00:01 UTC, stephenlauck commented on webserver.sh
> +ssh -i ./id_ed25519 adam@$RELATIVEPATH_IP
Is there an shell environment variable we could use here instead?

2023-05-22 23:10 UTC, rwc commented
Reviewed this PR w/ Monday Class and we've combined changes into https://github.com/slashrelativepath/relativepath-cycle-3/pull/23

2023-05-22 23:10 UTC, closed without merging