Make installing/updating/upgrading brew non-interactive
slashrelativepath/relativepath-cycle-3 pull request #26
Opened 2023-05-23 08:40 UTC by Sanlung

2023-05-23 14:55 UTC, stephenlauck requested changes
https://github.com/Homebrew/install/#install-homebrew-on-macos-or-linux

I think we should add this ENV VAR to the install command:

`NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

2023-05-23 15:16 UTC, Sanlung commented
Is it so? I can't test to see the difference as I think I don't want to uninstall Homebrew so I lose all the formulae I've installed. And what about the echos that I edited out? Were those done inappropriately, then?

2023-05-23 23:49 UTC, stephenlauck commented
Let's rebase this branch with main and refactor on next session.

2023-05-24 22:42 UTC, stephenlauck approved these changes
Great job!

2023-05-24 22:42 UTC, merged